#+TITLE: Notes for Privacy Paper

* Brainstorm

 - Encryption as an indispensable means to the end of privacy
 - Do I need to spend time on /digital privacy as a right/?
 - I should identify stakeholders and who should care about privacy:
   + Ordinary citizens and how they use encryption
     * Interpersonal communications
     * Online services (e.g. banking)
   + Corporations
     * Protecting user data (/ahem/ Equifax!)
     * Preventing bad actors from damaging our digital infrastructure.

 - It is a contradiction in will for the Attorney General to want access to every piece of encrypted communication while at the same time wanting to protect the US from foreign interference.

 - Case study: Apple vs. FBI in the San Bernardino Case

* Outline

 - Summary of case study: San Bernardino Case
 - Generalize: government has pushed for "responsible encryption" "warrant-compatible encryption"
 - Exploration of conflicting ethical values
   + Justice Department's arguments:
     * Protection of the people
     * Laws demand that Apple and technology suppliers respond to All Writs Act, subpoenas, etc.
   + Apple's arguments:
     * Free speech: Apple doesn't want to create software it considers to be unethical
     * Duty to protect everyone's privacy
 - Technical issues around government's request
   + Keys under doormats
   + Discussion of the importance of mechanisms to protect us against violations of our rights
 - Generalize responsibility of companies to protect user data
   + Equifax breach as example of what happens when encryption is /not/ used
   + GDPR requirements (← ?)
   + Encryption provides privacy from prying governments and prying applications and corporations
 - Resolution of case study
   + Government was able to crack encryption with large investment of resources
   + battle continues today; EARN-IT is the latest thrust

* Outline 2

** Structure

 - Let's do a delayed thesis
 - Bring up opposing stories:
   1. Child pornography
   2. Equifax breach
   3. San Bernardino Shooter
   4. Social credit system in China; Russian interference in 2016 elections; communication censorship

Ideas for graphics:

 - Number of people affected by Equifax breach vs. number of people affected by revenge porn, etc.

** Body

 - Conclusion: weakening encryption will weaken the means by which we can solve the root of these problems
 - The difficulty lies in that the victims of weakening encryption are often further removed from the problem than the victims of /not/

* Data

** Graphic on number of encrypted servers in use                                            :ATTACH:
   :PROPERTIES:
   :ID:       D35F1193-F0FC-4876-850D-7E579FD61C4D
   :END:


* Notes from Dr. Gates

 - Build an executive summary
 - Remember, 4-5 pages
 - Works cited can go at the end; each section should have its own sectionin the works cited section
 - Alternatively, you can do works cited at the end of each section

* Notes about the final

 - Final exam will be open all finals week
 - Time limit of 3 hours
 - Only about 25% is comprehensive
